version: '2.1'
services:
  licensingservice:
    image: licensing:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_CLOUD_CONFIG_URI:
        http://configserver:8071
    networks:
      backend:
        aliases:
         - "licenseservice"
networks:
  backend:
    driver: bridge
#docker-compose up
#mvn clean package dockerfile:build
#docker-compose -f docker/docker-compose.yml up